services:

  postgres:
    image: postgres:17
    container_name: cloudos-postgres

    environment:
      POSTGRES_DB: cloudos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/CloudOS.API

    ports:
      - "5000:8080"

    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

volumes:
  postgres_data: